### PR TITLE
SSDT-IGPU.dsl: Added 0x59160000

### PR DESCRIPTION
**Pull request by the-darkvoid**
Updated SSDT-IGPU to add a Kabylake Intel UHD Graphics 620.

### CODE REVIEW

**Comment by RehabMan** [comment]
Did you need changes to FakePCIID_Intel_HD_Graphics Info.plist as well?
I didn't see any commit there, so ... curious.

**Comment by the-darkvoid** [comment]
I did, added this in the .plist:

		<key>UHD620</key>
		<dict>
			<key>CFBundleIdentifier</key>
			<string>org.rehabman.driver.FakePCIID</string>
			<key>FakeProperties</key>
			<dict>
				<key>RM,device-id</key>
				<data>
				FlkAAA==
				</data>
			</dict>
			<key>IOClass</key>
			<string>FakePCIID</string>
			<key>IOMatchCategory</key>
			<string>FakePCIID</string>
			<key>IOPCIClassMatch</key>
			<string>0x03000000&amp;0xff000000</string>
			<key>IOPCIPrimaryMatch</key>
			<string>0x59168086 0x59178086</string>
			<key>IOProbeScore</key>
			<integer>9001</integer>
			<key>IOProviderClass</key>
			<string>IOPCIDevice</string>
		</dict>

**Comment by RehabMan** [comment]
I figured that was the case, but didn't see a commit in your FakePCIID repo...

**Comment by RehabMan** [comment]
Did major cleanup to SSDT-IGPU to move Skylake spoof to a separate file.
Included support for 0x5917 at the same time.
Also revised FakePCIID.
Thanks for confirming the 0x5917 as 0x5916 works!

**Pull request closed without merging**
